
import java.util.ArrayList;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.Marshaller;

import de.lindow_it.obiee.rtf.model.RtfConfiguration;
import de.lindow_it.obiee.rtf.model.RtfVariable;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        
    	
    	RtfConfiguration configuration = new RtfConfiguration();
    	configuration.setRtfFileName("test.rtf");
    	
    	configuration.getVariables().put("test", "test");
    	configuration.getVariables().put("tester", "${test} + ${test}");
    	
    	
    	try {
	        JAXBContext context = JAXBContext.newInstance(RtfConfiguration.class);
	        Marshaller m = context.createMarshaller();
	        m.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
	        
	        m.marshal(configuration, System.out);
    	} catch (Exception ex) {
    		ex.printStackTrace();
    	}
    	
    }
}
